version: '3.8'

services:
  postgresql:
    image: postgres:16
    container_name: postgresql
    restart: unless-stopped
    environment:
      # IMPORTANT: Change these values before deploying!
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      POSTGRES_DB: ${POSTGRES_DB:-homelab}
      # Performance tuning
      POSTGRES_INITDB_ARGS: "-E UTF8 --locale=en_US.UTF-8"
    ports:
      - "5432:5432"
    volumes:
      # Persist data
      - postgresql_data:/var/lib/postgresql/data
      # Custom configuration (optional)
      - ./postgresql.conf:/etc/postgresql/postgresql.conf:ro
      # Initialization scripts (optional)
      - ./init-scripts:/docker-entrypoint-initdb.d:ro
    # Resource limits (adjust based on VM resources)
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 6G
        reservations:
          cpus: '2'
          memory: 4G
    # Health check
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - homelab_network

  # Optional: pgAdmin for database management
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@homelab.local}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-changeme}
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      postgresql:
        condition: service_healthy
    networks:
      - homelab_network

volumes:
  postgresql_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  homelab_network:
    driver: bridge
